pub use embedded_hal as wg;

pub mod reg_proxy {
    /// Implemented for registers that `RegProxy` can proxy.
    ///
    /// Use the `reg!` macro to implement this trait for a register from a crate
    /// generated by svd2rust.
    ///
    /// # Safety
    /// The pointer returned by `get` must be valid for the duration of the program.
    pub unsafe trait Reg {
        /// Type that `RegProxy` should dereference to.
        type Target;

        /// Pointer to the register memory location.
        fn get() -> *const Self::Target;
    }

    /// Like [`Reg`], for register clusters (arrays of identical registers).
    pub unsafe trait RegCluster {
        type Target;

        fn get() -> *const [Self::Target];
    }
}
