name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: cargo check (thumbv6m-none-eabi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv6m-none-eabi

      - name: Check
        run: cargo check --target thumbv6m-none-eabi
